### PR TITLE
Deal with no compatible galaxies, add AGN_flag for mangrove

### PR DESCRIPTION
**Pull request by jgducoin**
For the event S200106av, looking at the observation plan produced (cf attached image)Screenshot from 2020-01-14 10-05-02, it looks crazy. The problem comes from the fact that the skymap and distance error are so small that there are no compatible galaxies. Looking at the gwemopt code it seems that there is a "security" (here: https://github.com/mcoughlin/gwemopt/blob/master/gwemopt/catalog.py#L251) which put Sloc to 1 for all galaxies in such case. This led to point everywhere in the sky. 
This is probably a marginal effect because such skymap comes only from a non-astrophysical event, but it looks weird for people not aware of that to receive such obsplan.

Changes proposed in this pull request:

- catalog.py now output an empty table when no galaxies are compatible. (I did check quickly that thing are working with this output but I did not do any digging with all possibility of the code)
- If there are no compatible galaxies, the ToO_manager code use the 2D probability to compute the tiling obsplan

Other change:
- The mangrove catalog now has an "AGN_flag" column. I added the possibility to output this with  
params["AGN_flag"] = True.

### CODE REVIEW

**Comment by mcoughlin** [comment]
So I think it still makes sense to set the numbers to 1 but also print some kind of big warning when this occurs? Folks will still run the code, and other codes will fail if nothing comes out of the catalogs call. Maybe better is to have ToO_Manager interpret this case?

**Comment by dcorre** [comment]
Hi @mcoughlin , could we simply add a new keyword `CompatibleGal` (True/False) in the catalog.py's output dictionnaries map_struct or catalog_struct?

**Comment by mcoughlin** [comment]
I think this could work. Are you proposing to leave the non-zero catalog numbers still to keep backwards compatibility?

**Comment by dcorre** [comment]
Yes, if returning an empy dictionnary may crash the code some other people are using, we could simply add a flag in the output dict, and use its value in ToO_manager. If this fine for you, @jgducoin can implement it.

**Comment by jgducoin** [comment]
Yes I will put back the "security" (here: https://github.com/mcoughlin/gwemopt/blob/master/gwemopt/catalog.py#L251) and add the keyword.

**Comment by jgducoin** [comment]
@mcoughlin done in the last commit. Should work as expected now.

**Pull request merged**
