### PR TITLE
Linking the GRANDMA ObsStrat, first grade

### PR DESCRIPTION
**Pull request by jgducoin**
I linked the first version of the GRANDMA Grade here. The second one is suppose to be linked to but i still have to test it. For that i need @santier14 to point on a good skymap (one with distance info). I putted here the GW170817 skymap for example (it is a bit heavy so maybe you don't want it to stay on the git @mcoughlin). Of course the main changes were done on the GRANDMA ObsStrat itself (I will make a merge request on the GRANDMA gitlab just after that).

### CODE REVIEW

**Comment by jgducoin** [comment]
I you do want to use the code without my changes just put GRANDMA=False at line 213

**Comment by mcoughlin** [comment]
@jgducoin I think the "GRANDMA" strategy should be in gwemopt directly right? And called something more like "catalog" or similar? I am fine with the example GW170817 skymap.

**Comment by santier14** [comment]
@jgducoin I would like to use this skymap https://emfollow.docs.ligo.org/userguide/_static/bayestar.fits.gz because it is an exemple for O3 skymap format. And it seems there is the distance in the header as well

**Comment by mcoughlin** [comment]
I am closing this, as I don't think it applies anymore.

**Pull request closed without merging**
