### PR TITLE
fixing the ud_grade power

### PR DESCRIPTION
**Pull request by jgducoin**
@mcoughlin

### CODE REVIEW

**Comment by lpsinger** [comment]
There's a bit more to this... see `ligo.skymap.distance.ud_grade`.

**Comment by jgducoin** [comment]
@mcoughlin Did you ever tested `ligo.skymap.distance.ud_grade`? If yes do you plan to use this function instead of the healpy one?

**Comment by mcoughlin** [comment]
@jgducoin I haven't looked at it in detail, but it seems the clear choice here. Can you give it a try and then add it to the pull request?

**Comment by jgducoin** [comment]
Yes, I'll do that.

**Pull request closed without merging**
